### ISSUE TITLE
BEAST related error

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/mcbette#4]
Upon running mcbette::est_marg_liks:

`mcbette::est_marg_liks(fasta_filename = "rag1_trimal.fasta")`

I receive the following error:

```
Error: Could not find or load main class beast.util.PackageManager
Error: mauricer::is_beast2_pkg_installed("NS") are not all TRUE
In addition: Warning message:
In system2(command = beastier::get_default_java_path(), args = c("-cp",  :
  running command ''/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' -cp '/Users/janzen/Library/Application Support/BEAST/lib/beast.jar' beast.util.PackageManager -list' had status 1
```

**Comment by thijsjanzen** [comment]
> Upon running mcbette::est_marg_liks:
> 
> `mcbette::est_marg_liks(fasta_filename = "rag1_trimal.fasta")`
> 
> I receive the following error:
> 
> ```
> Error: Could not find or load main class beast.util.PackageManager
> Error: mauricer::is_beast2_pkg_installed("NS") are not all TRUE
> In addition: Warning message:
> In system2(command = beastier::get_default_java_path(), args = c("-cp",  :
>   running command ''/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' -cp '/Users/janzen/Library/Application Support/BEAST/lib/beast.jar' beast.util.PackageManager -list' had status 1
> ```

I suspect it has something to do with the installation folders of BEAST and/or Java...
I have tried installing BEAST using beastier, but this gives the report that BEAST is already installed (which is correct). 
Alternatively, I have used beastier to install beast in a custom folder, but in mcbette I can not specify the path of BEAST.

**Comment by richelbilderbeek** [comment]
Thanks for this Issue!

This is not a `mcbette` error: Travis proves `mcbette` works on such a simple example.

Instead, the error was at my side, as I hadn't put any installation instructions anywhere. They are [here](https://github.com/richelbilderbeek/mcbette#how-to-use-mcbette-offline). Do that on a UNIX machine and it should work. If not, go ahead and create a new Issues :+1:

Closing this one now, feel free to re-open iff there are questions about my answer :rainbow:

**Comment by thijsjanzen** [comment]
I'm afraid that doesn't solve the issue, upon `mauricer::install_beast2_pkg("NS")` I receive:

```
Error: Could not find or load main class beast.util.PackageManager
Error in if (is_beast2_pkg_installed(name)) { : 
  argument is of length zero
In addition: Warning message:
In system2(command = beastier::get_default_java_path(), args = c("-cp",  :
  running command ''/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' -cp '/Users/janzen/Library/Application Support/BEAST/lib/beast.jar' beast.util.PackageManager -list' had status 1
```



(also, interestingly from the installation instructions, the line 'devtools::install_github("richelbilderbeek/mcbette") are missing ;) )

**Comment by richelbilderbeek** [comment]
Hmmm, I see I do not build `mcbette` under macOS. Add this to the test and [running it now ](https://travis-ci.org/richelbilderbeek/mcbette/builds/493847272). I'll keep you posted.

Fixed the doc :+1:

**Comment by thijsjanzen** [comment]
Still doesn't work... :

`mauricer::install_beast2_pkg("NS")
Error: Could not find or load main class beast.util.PackageManager
Error in if (is_beast2_pkg_installed(name)) { : 
  argument is of length zero
In addition: Warning message:
In system2(command = beastier::get_default_java_path(), args = c("-cp",  :
  running command ''/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' -cp '/Users/janzen/Library/Application Support/BEAST/lib/beast.jar' beast.util.PackageManager -list' had status 1`

`mcbette::est_marg_liks(fasta_filename = "test.fasta")
Error: Could not find or load main class beast.util.PackageManager
Error: mauricer::is_beast2_pkg_installed("NS") are not all TRUE
In addition: Warning message:
In system2(command = beastier::get_default_java_path(), args = c("-cp",  :
  running command ''/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/bin/java' -cp '/Users/janzen/Library/Application Support/BEAST/lib/beast.jar' beast.util.PackageManager -list' had status 1`

**Comment by richelbilderbeek** [comment]
Both Travis builds work fine: [develop, 164](https://travis-ci.org/richelbilderbeek/mcbette/builds/495596529) and [master, 154](https://travis-ci.org/richelbilderbeek/mcbette/builds/493219678).

I wonder if it has to do with the spaces in your path to BEAST2, `/Users/janzen/Library/Application Support/BEAST/lib/beast.jar`. Is the the default location `beastier` installs BEAST2 to?
